#!/bin/bash
# ============================================================
# setup.sh — Cài đặt 1 lần toàn bộ hệ thống trên server Debian
# ------------------------------------------------------------
# Tự động: cài Docker/Compose, clone repo, tạo .env (sinh secret),
# tạo volume, sinh SSL cert, khởi động toàn bộ container.
# Chỉ cần chạy 1 lệnh duy nhất:
#
#   curl -fsSL https://raw.githubusercontent.com/ththuan/quanlytaisan2026/main/setup.sh -o setup.sh
#   sudo bash setup.sh
#
# Sau khi chạy xong, server đã sẵn sàng. Mọi thay đổi code về sau chỉ cần
# push lên GitHub là tự deploy (nếu đã cài self-hosted runner ở bước cuối).
# ============================================================

set -euo pipefail

# ---------- Cấu hình mặc định (có thể ghi đè bằng biến môi trường) ----------
REPO_URL="${REPO_URL:-https://github.com/ththuan/quanlytaisan2026.git}"
APP_DIR="${APP_DIR:-/root/quanlytaisan2026}"
DOMAIN="${DOMAIN:-quanlytaisanctec.dpdns.org}"
COMPOSE_FILE="docker-compose.prod.yml"

# Secrets (để trống sẽ tự sinh ngẫu nhiên — KHÔNG dùng mặc định yếu)
DB_PASSWORD="${DB_PASSWORD:-}"
JWT_SECRET="${JWT_SECRET:-}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"
DEFAULT_PASSWORD="${DEFAULT_PASSWORD:-}"
CF_TUNNEL_TOKEN="${CF_TUNNEL_TOKEN:-}"

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${CYAN}[setup]${NC} $*"; }
ok()   { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; }

if [ "$(id -u)" -ne 0 ]; then
    err "Phải chạy với quyền root: sudo bash setup.sh"
    exit 1
fi

# ---------- 1. Cài Docker + Docker Compose plugin ----------
install_docker() {
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        ok "Docker + Compose đã có sẵn."
        return
    fi
    log "Cài Docker Engine + Compose plugin..."
    apt-get update
    apt-get install -y ca-certificates curl gnupg
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable --now docker
    ok "Docker đã cài xong."
}

# ---------- 2. Cài git / curl (nếu thiếu) ----------
install_tools() {
    apt-get install -y git curl openssl >/dev/null 2>&1 || true
    ok "git/curl/openssl sẵn sàng."
}

# ---------- 3. Clone / cập nhật repo ----------
prepare_repo() {
    if [ -d "$APP_DIR/.git" ]; then
        ok "Repo đã tồn tại tại $APP_DIR"
        return
    fi
    log "Clone repo..."
    mkdir -p "$APP_DIR"
    git clone "$REPO_URL" "$APP_DIR"
    ok "Đã clone repo vào $APP_DIR"
}

# ---------- 4. Sinh secret nếu chưa có ----------
ensure_secrets() {
    [ -z "$DB_PASSWORD" ]      && DB_PASSWORD="$(openssl rand -hex 16)"
    [ -z "$JWT_SECRET" ]        && JWT_SECRET="$(openssl rand -hex 32)"
    [ -z "$DEFAULT_PASSWORD" ]  && DEFAULT_PASSWORD="$(openssl rand -base64 15 | tr -d '/+=')!Aa1"
    [ -z "$ADMIN_PASSWORD" ]    && ADMIN_PASSWORD="$(openssl rand -base64 15 | tr -d '/+=')!Aa1"
}

# ---------- 5. Tạo / tự sửa file .env ----------
write_env() {
    local env_file="$APP_DIR/.env"
    if [ -f "$env_file" ]; then
        warn "$env_file đã tồn tại — tự động kiểm tra & sửa secret yếu..."
        ENV_FILE="$env_file" bash "$APP_DIR/scripts/fix-env-secrets.sh"
        return
    fi
    log "Tạo $env_file với secret ngẫu nhiên..."
    cat > "$env_file" <<EOF
# Auto-generated by setup.sh — $(date '+%Y-%m-%d %H:%M:%S')
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=asset_management

NODE_ENV=production
JWT_SECRET=${JWT_SECRET}
DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
LOG_LEVEL=info

CORS_ORIGIN=https://${DOMAIN}
FRONTEND_URL=https://${DOMAIN}

CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
EOF
    chmod 600 "$env_file"
    ok "Đã tạo $env_file"
}

# ---------- 6. Tạo Docker volumes ----------
create_volumes() {
    log "Tạo Docker volumes (nếu chưa có)..."
    docker volume create quanlytaisan_postgres_data >/dev/null
    docker volume create quanlytaisan_redis_data >/dev/null
    docker volume create quanlytaisan_backend_backups >/dev/null
    ok "Volumes đã sẵn sàng."
}

# ---------- 7. Sinh SSL cert tự ký (nginx cần để chạy) ----------
generate_ssl() {
    local ssl_dir="$APP_DIR/nginx/ssl"
    if [ -f "$ssl_dir/server.crt" ] && [ -f "$ssl_dir/server.key" ]; then
        ok "SSL cert đã có sẵn."
        return
    fi
    log "Sinh SSL cert tự ký (10 năm)..."
    mkdir -p "$ssl_dir"
    openssl req -x509 -nodes -newkey rsa:2048 -days 3650 \
        -keyout "$ssl_dir/server.key" \
        -out "$ssl_dir/server.crt" \
        -subj "/CN=${DOMAIN}" \
        -addext "subjectAltName=DNS:${DOMAIN},DNS:localhost,IP:127.0.0.1" >/dev/null 2>&1
    ok "Đã tạo nginx/ssl/server.crt + server.key"
}

# ---------- 8. Khởi động dịch vụ ----------
start_services() {
    cd "$APP_DIR"
    log "Build + khởi động container (production)..."
    if [ -n "$CF_TUNNEL_TOKEN" ]; then
        docker compose -f "$COMPOSE_FILE" --profile cloudflare up -d --build
    else
        docker compose -f "$COMPOSE_FILE" up -d --build
    fi
    ok "Container đã khởi động."
}

# ---------- 9. Gợi ý cài self-hosted runner ----------
offer_runner() {
    echo ""
    warn "Chưa cài GitHub self-hosted runner => chưa auto-deploy."
    echo "Muốn 'push code là tự deploy' không cần SSH thủ công, hãy cài runner:"
    echo "  1) GitHub repo -> Settings -> Actions -> Runners -> New self-hosted runner (Linux x64)"
    echo "  2) Copy TOKEN, rồi chạy:"
    echo "     RUNNER_TOKEN=<TOKEN> bash $APP_DIR/scripts/setup-github-runner.sh"
    echo ""
}

# ============================================================
# Main
# ============================================================
log "Bắt đầu cài đặt — domain: ${DOMAIN}"
install_docker
install_tools
prepare_repo
ensure_secrets
write_env
create_volumes
generate_ssl
start_services

# Đọc lại giá trị thực từ .env (để in đúng, kể cả khi .env cũ được auto-sửa)
if [ -f "$APP_DIR/.env" ]; then
    ADMIN_PASSWORD="$(sed -n 's/^ADMIN_PASSWORD=//p' "$APP_DIR/.env" | tail -n1)"
    DEFAULT_PASSWORD="$(sed -n 's/^DEFAULT_PASSWORD=//p' "$APP_DIR/.env" | tail -n1)"
fi

echo ""
ok "CÀI ĐẶT HOÀN TẤT."
echo -e "  Truy cập nội bộ:  https://<IP-server>"
echo -e "  Truy cập public:  https://${DOMAIN}"
echo -e "  Đăng nhập admin:  admin / ${ADMIN_PASSWORD}"
echo -e "  Mật khẩu user mới (DEFAULT_PASSWORD): ${DEFAULT_PASSWORD}"
echo -e "  Xem log:          docker compose -f $APP_DIR/$COMPOSE_FILE logs -f"
echo -e "  (Mọi secret lưu trong $APP_DIR/.env)"
echo ""

if [ -n "$CF_TUNNEL_TOKEN" ]; then
    log "Kiểm tra tunnel: docker logs asset-management-cloudflared -f (phải thấy 'Registered tunnel connection')"
else
    warn "CF_TUNNEL_TOKEN chưa được cấu hình => chỉ chạy nội bộ/LAN."
    warn "Để public ra internet: thêm CF_TUNNEL_TOKEN vào $APP_DIR/.env rồi chạy:"
    warn "  docker compose -f $APP_DIR/$COMPOSE_FILE --profile cloudflare up -d"
fi

offer_runner
