'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    // Create sample assets
    await queryInterface.bulkInsert('assets', [
      {
        id: 1,
        asset_code: 'IT-001',
        name: 'Laptop Dell XPS 15',
        category: 'electronics',
        description: 'Laptop Dell XPS 15 Core i7, 16GB RAM, 512GB SSD',
        purchase_date: new Date('2024-01-15'),
        purchase_price: 35000000,
        current_value: 30000000,
        current_department_id: 1,
        status: 'active',
        serial_number: 'DL-XPS-2024-001',
        warranty_date: new Date('2027-01-15'),
        location: 'Phòng IT - Tầng 2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        asset_code: 'IT-002',
        name: 'Máy in HP LaserJet Pro',
        category: 'electronics',
        description: 'Máy in laser HP LaserJet Pro M404dn',
        purchase_date: new Date('2024-02-20'),
        purchase_price: 8500000,
        current_value: 7500000,
        current_department_id: 1,
        status: 'active',
        serial_number: 'HP-LJ-2024-002',
        warranty_date: new Date('2026-02-20'),
        location: 'Phòng IT - Tầng 2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        asset_code: 'IT-003',
        name: 'Màn hình Dell 27 inch',
        category: 'electronics',
        description: 'Màn hình Dell UltraSharp 27 inch 4K',
        purchase_date: new Date('2024-03-10'),
        purchase_price: 12000000,
        current_value: 11000000,
        current_department_id: 1,
        status: 'active',
        serial_number: 'DL-MON-2024-003',
        warranty_date: new Date('2027-03-10'),
        location: 'Phòng IT - Tầng 2',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        asset_code: 'ACCT-001',
        name: 'Laptop Lenovo ThinkPad',
        category: 'electronics',
        description: 'Laptop Lenovo ThinkPad T14, Core i5, 8GB RAM',
        purchase_date: new Date('2023-11-05'),
        purchase_price: 22000000,
        current_value: 18000000,
        current_department_id: 2,
        status: 'active',
        serial_number: 'LN-TP-2023-004',
        warranty_date: new Date('2026-11-05'),
        location: 'Phòng Kế toán - Tầng 3',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        asset_code: 'ACCT-002',
        name: 'Bàn làm việc 1.4m',
        category: 'furniture',
        description: 'Bàn làm việc gỗ công nghiệp 1.4m',
        purchase_date: new Date('2022-06-15'),
        purchase_price: 3500000,
        current_value: 2500000,
        current_department_id: 2,
        status: 'active',
        serial_number: null,
        warranty_date: null,
        location: 'Phòng Kế toán - Tầng 3',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 6,
        asset_code: 'HR-001',
        name: 'Tủ hồ sơ 4 ngăn',
        category: 'furniture',
        description: 'Tủ đựng hồ sơ kim loại 4 ngăn kéo',
        purchase_date: new Date('2022-03-20'),
        purchase_price: 4200000,
        current_value: 3000000,
        current_department_id: 3,
        status: 'active',
        serial_number: null,
        warranty_date: null,
        location: 'Phòng Nhân sự - Tầng 3',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 7,
        asset_code: 'HR-002',
        name: 'Máy chiếu Epson',
        category: 'electronics',
        description: 'Máy chiếu Epson EB-X51 XGA',
        purchase_date: new Date('2023-08-10'),
        purchase_price: 15000000,
        current_value: 12000000,
        current_department_id: 3,
        status: 'active',
        serial_number: 'EP-X51-2023-007',
        warranty_date: new Date('2025-08-10'),
        location: 'Phòng họp - Tầng 3',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 8,
        asset_code: 'MKT-001',
        name: 'iMac 24 inch M1',
        category: 'electronics',
        description: 'Apple iMac 24 inch M1 chip, 8GB RAM, 256GB SSD',
        purchase_date: new Date('2024-04-01'),
        purchase_price: 42000000,
        current_value: 38000000,
        current_department_id: 4,
        status: 'active',
        serial_number: 'AP-IMAC-2024-008',
        warranty_date: new Date('2026-04-01'),
        location: 'Phòng Marketing - Tầng 4',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 9,
        asset_code: 'MKT-002',
        name: 'Camera Canon EOS R6',
        category: 'equipment',
        description: 'Máy ảnh Canon EOS R6 Mark II Full Frame',
        purchase_date: new Date('2024-05-15'),
        purchase_price: 65000000,
        current_value: 60000000,
        current_department_id: 4,
        status: 'active',
        serial_number: 'CN-R6-2024-009',
        warranty_date: new Date('2026-05-15'),
        location: 'Phòng Marketing - Tầng 4',
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 10,
        asset_code: 'ADM-001',
        name: 'Điều hòa Daikin Inverter',
        category: 'equipment',
        description: 'Điều hòa Daikin Inverter 12000 BTU',
        purchase_date: new Date('2023-05-20'),
        purchase_price: 18000000,
        current_value: 15000000,
        current_department_id: 5,
        status: 'active',
        serial_number: 'DK-INV-2023-010',
        warranty_date: new Date('2026-05-20'),
        location: 'Phòng Hành chính - Tầng 1',
        created_at: new Date(),
        updated_at: new Date(),
      },
    ], {});

    // Reset sequence for PostgreSQL
    await queryInterface.sequelize.query(
      `SELECT setval('assets_id_seq', (SELECT MAX(id) FROM assets));`
    );

    console.log('✅ Assets seeded successfully');
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('assets', null, {});
  }
};
